// flow-typed signature: 6518e95fd6ad7f910d137b00f2216a1c
// flow-typed version: <<STUB>>/thunkify_v^2.1.2/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'thunkify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'clone' {
  declare module.exports: any;
}
