// flow-typed signature: 01a796a5206d94f7f6741c06b2625951
// flow-typed version: <<STUB>>/eslint-config-vx_vgit+http://192.168.101.103/vx/eslint-config-vx/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-vx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-vx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-vx/lib/legacy' {
  declare module.exports: any;
}

declare module 'eslint-config-vx/lib/rules/best-practices' {
  declare module.exports: any;
}

declare module 'eslint-config-vx/lib/rules/errors' {
  declare module.exports: any;
}

declare module 'eslint-config-vx/lib/rules/es6' {
  declare module.exports: any;
}

declare module 'eslint-config-vx/lib/rules/node' {
  declare module.exports: any;
}

declare module 'eslint-config-vx/lib/rules/strict' {
  declare module.exports: any;
}

declare module 'eslint-config-vx/lib/rules/style' {
  declare module.exports: any;
}

declare module 'eslint-config-vx/lib/rules/variables' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-vx/index' {
  declare module.exports: $Exports<'eslint-config-vx'>;
}
declare module 'eslint-config-vx/index.js' {
  declare module.exports: $Exports<'eslint-config-vx'>;
}
declare module 'eslint-config-vx/lib/legacy.js' {
  declare module.exports: $Exports<'eslint-config-vx/lib/legacy'>;
}
declare module 'eslint-config-vx/lib/rules/best-practices.js' {
  declare module.exports: $Exports<'eslint-config-vx/lib/rules/best-practices'>;
}
declare module 'eslint-config-vx/lib/rules/errors.js' {
  declare module.exports: $Exports<'eslint-config-vx/lib/rules/errors'>;
}
declare module 'eslint-config-vx/lib/rules/es6.js' {
  declare module.exports: $Exports<'eslint-config-vx/lib/rules/es6'>;
}
declare module 'eslint-config-vx/lib/rules/node.js' {
  declare module.exports: $Exports<'eslint-config-vx/lib/rules/node'>;
}
declare module 'eslint-config-vx/lib/rules/strict.js' {
  declare module.exports: $Exports<'eslint-config-vx/lib/rules/strict'>;
}
declare module 'eslint-config-vx/lib/rules/style.js' {
  declare module.exports: $Exports<'eslint-config-vx/lib/rules/style'>;
}
declare module 'eslint-config-vx/lib/rules/variables.js' {
  declare module.exports: $Exports<'eslint-config-vx/lib/rules/variables'>;
}
