// flow-typed signature: 5474b3197e3aef436bcca75ad51bc1b1
// flow-typed version: <<STUB>>/gulp-uglify_v^2.0.1/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-uglify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-uglify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-uglify/lib/create-error' {
  declare module.exports: any;
}

declare module 'gulp-uglify/lib/gulp-uglify-error' {
  declare module.exports: any;
}

declare module 'gulp-uglify/lib/log' {
  declare module.exports: any;
}

declare module 'gulp-uglify/minifier' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-uglify/index' {
  declare module.exports: $Exports<'gulp-uglify'>;
}
declare module 'gulp-uglify/index.js' {
  declare module.exports: $Exports<'gulp-uglify'>;
}
declare module 'gulp-uglify/lib/create-error.js' {
  declare module.exports: $Exports<'gulp-uglify/lib/create-error'>;
}
declare module 'gulp-uglify/lib/gulp-uglify-error.js' {
  declare module.exports: $Exports<'gulp-uglify/lib/gulp-uglify-error'>;
}
declare module 'gulp-uglify/lib/log.js' {
  declare module.exports: $Exports<'gulp-uglify/lib/log'>;
}
declare module 'gulp-uglify/minifier.js' {
  declare module.exports: $Exports<'gulp-uglify/minifier'>;
}
