// flow-typed signature: c8ab439564d2de97e39b01d788a5bf60
// flow-typed version: <<STUB>>/gulp-header_v^1.8.8/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-header'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-header' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-header/index' {
  declare module.exports: $Exports<'gulp-header'>;
}
declare module 'gulp-header/index.js' {
  declare module.exports: $Exports<'gulp-header'>;
}
