// flow-typed signature: fab3874b4088a7e5c18de38bbff240c4
// flow-typed version: <<STUB>>/pump_v^1.0.2/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pump'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'pump' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pump/test-browser' {
  declare module.exports: any;
}

declare module 'pump/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pump/index' {
  declare module.exports: $Exports<'pump'>;
}
declare module 'pump/index.js' {
  declare module.exports: $Exports<'pump'>;
}
declare module 'pump/test-browser.js' {
  declare module.exports: $Exports<'pump/test-browser'>;
}
declare module 'pump/test.js' {
  declare module.exports: $Exports<'pump/test'>;
}
