// flow-typed signature: 6518e95fd6ad7f910d137b00f2216a1c
// flow-typed version: <<STUB>>/thunkify_v^2.1.2/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'thunkify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'thunkify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'thunkify/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'thunkify/index' {
  declare module.exports: $Exports<'thunkify'>;
}
declare module 'thunkify/index.js' {
  declare module.exports: $Exports<'thunkify'>;
}
declare module 'thunkify/test/index.js' {
  declare module.exports: $Exports<'thunkify/test/index'>;
}
